import type { UserOrder } from "./types";

export const MOCK_USER_ORDERS: UserOrder[] = [
  {
    id: "ORD-98421",
    date: "Aug 16, 2026 at 2:30 PM",
    storeName: "POCO Official Store",
    storeSlug: "poco-official-store",
    status: "processing",
    estimatedDelivery: "Aug 19, 2026",
    shippingAddress: "Vanneth Sok (096 888 7777) - House #42B, Street 271, Tuol Sangkae 2, Ruessei Kaev, Phnom Penh",
    paymentMethod: "Pay Now with Shop (DIRECT KHQR)",
    total: 216.75,
    subtotal: 255.0,
    discount: 38.25,
    shippingFee: 0.0,
    trackingNumber: "VET-KH-88912",
    courier: "VET Express Cambodia",
    items: [
      {
        id: 1,
        title: "POCO Smart Phone X5 Pro 5G 256GB Yellow",
        price: 216.75,
        quantity: 1,
        image: "/picture/pic1.jpg",
        slug: "poco-smart-phone-x5-pro",
      },
    ],
  },
  {
    id: "ORD-97305",
    date: "Aug 12, 2026 at 10:14 AM",
    storeName: "iOne Apple Reseller",
    storeSlug: "ione-apple-reseller",
    status: "shipped",
    estimatedDelivery: "Aug 18, 2026 (Today)",
    shippingAddress: "Vanneth Sok (012 345 6789) - Canadia Tower, 18th Floor, Monivong Blvd, Wat Phnom, Daun Penh, Phnom Penh",
    paymentMethod: "Pay Now with Shop (DIRECT KHQR)",
    total: 2499.0,
    subtotal: 2499.0,
    discount: 0.0,
    shippingFee: 0.0,
    trackingNumber: "JT-KH-44019",
    courier: "J&T Express Cambodia",
    items: [
      {
        id: 2,
        title: 'MacBook Pro 16" M3 Max 36GB / 1TB SSD - Space Black',
        price: 2499.0,
        quantity: 1,
        image: "/picture/pic2.jpg",
        slug: "macbook-pro-16-m3-max",
      },
    ],
  },
  {
    id: "ORD-95112",
    date: "Aug 05, 2026 at 4:45 PM",
    storeName: "Audio Pro Phnom Penh",
    storeSlug: "audio-pro-phnom-penh",
    status: "delivered",
    estimatedDelivery: "Delivered on Aug 07, 2026",
    shippingAddress: "Vanneth Sok (096 888 7777) - House #42B, Street 271, Tuol Sangkae 2, Ruessei Kaev, Phnom Penh",
    paymentMethod: "Pay Now with Shop (DIRECT KHQR)",
    total: 307.12,
    subtotal: 349.0,
    discount: 41.88,
    shippingFee: 0.0,
    trackingNumber: "NHAM-88021",
    courier: "NHAM24 Express",
    items: [
      {
        id: 3,
        title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
        price: 307.12,
        quantity: 1,
        image: "/picture/pic7.jpg",
        slug: "sony-wh-1000xm5-wireless-headphones",
      },
    ],
  },
  {
    id: "ORD-93044",
    date: "Jul 28, 2026 at 11:20 AM",
    storeName: "Phnom Penh Sports City",
    storeSlug: "phnom-penh-sports-city",
    status: "delivered",
    estimatedDelivery: "Delivered on Jul 30, 2026",
    shippingAddress: "Vanneth Sok (096 888 7777) - House #42B, Street 271, Tuol Sangkae 2, Ruessei Kaev, Phnom Penh",
    paymentMethod: "Cash on Delivery (COD)",
    total: 227.2,
    subtotal: 238.0,
    discount: 10.8,
    shippingFee: 0.0,
    trackingNumber: "VET-KH-31092",
    courier: "VET Express Cambodia",
    items: [
      {
        id: 4,
        title: "Nike Air Zoom Pegasus 40 Road Running Shoes",
        price: 130.0,
        quantity: 1,
        image: "/picture/pic3.jpg",
        slug: "nike-air-zoom-pegasus-40",
      },
      {
        id: 5,
        title: "Fitbit Versa 4 Fitness Smartwatch",
        price: 97.2,
        quantity: 1,
        image: "/picture/pic4.jpg",
        slug: "fitbit-versa-4-fitness-smartwatch",
      },
    ],
  },
];
