import type { SavedItem } from "./types";

export const INITIAL_SAVED_ITEMS: SavedItem[] = [
  {
    id: 1,
    slug: "poco-smart-phone-x5-pro",
    title: "POCO Smart Phone X5 Pro 5G 256GB Yellow",
    description: "Snapdragon 778G, 120Hz FHD+ AMOLED DotDisplay, 108MP pro-grade camera.",
    price: 216.75,
    originalPrice: 255.0,
    discountPercent: 15,
    rating: 4.8,
    reviewCount: 42,
    category: "Phone & Tablets",
    image: "/picture/pic1.jpg",
    storeName: "POCO Official Store",
    inStock: true,
  },
  {
    id: 2,
    slug: "macbook-pro-16-m3-max",
    title: 'MacBook Pro 16" M3 Max 36GB / 1TB SSD - Space Black',
    description: "Liquid Retina XDR display, 16-core CPU, 40-core GPU, up to 22 hours battery life.",
    price: 2499.0,
    rating: 5.0,
    reviewCount: 18,
    category: "Computer & Accessories",
    image: "/picture/pic2.jpg",
    storeName: "iOne Apple Reseller",
    inStock: true,
  },
  {
    id: 3,
    slug: "fitbit-versa-4-fitness-smartwatch",
    title: "Fitbit Versa 4 Fitness Smartwatch with Built-in GPS",
    description: "Daily readiness score, 24/7 heart rate monitoring, 40+ exercise modes, 6+ day battery.",
    price: 97.2,
    originalPrice: 108.0,
    discountPercent: 10,
    rating: 4.6,
    reviewCount: 29,
    category: "Wearables",
    image: "/picture/pic4.jpg",
    storeName: "TechHub Cambodia",
    inStock: true,
  },
  {
    id: 4,
    slug: "sony-wh-1000xm5-wireless-headphones",
    title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
    description: "Two processors and 8 microphones for unprecedented noise cancellation and crystal clear calls.",
    price: 307.12,
    originalPrice: 349.0,
    discountPercent: 12,
    rating: 4.9,
    reviewCount: 64,
    category: "Electronic & Appliances",
    image: "/picture/pic7.jpg",
    storeName: "Audio Pro Phnom Penh",
    inStock: true,
  },
  {
    id: 5,
    slug: "nike-air-zoom-pegasus-40",
    title: "Nike Air Zoom Pegasus 40 Road Running Shoes",
    description: "Engineered mesh upper, dual Zoom Air units, durable rubber waffle-inspired outsole.",
    price: 130.0,
    rating: 4.7,
    reviewCount: 35,
    category: "Fashion & Beauty",
    image: "/picture/pic3.jpg",
    storeName: "Phnom Penh Sports City",
    inStock: true,
  },
  {
    id: 6,
    slug: "lg-smart-oled-4k-tv-55",
    title: 'LG OLED evo C3 55" 4K Smart TV 2024 Model',
    description: "Self-lit OLED pixels, α9 AI Processor Gen6, Brightness Booster, Dolby Vision & Atmos.",
    price: 559.2,
    originalPrice: 699.0,
    discountPercent: 20,
    rating: 4.8,
    reviewCount: 51,
    category: "Electronic & Appliances",
    image: "/picture/pic8.jpg",
    storeName: "LG Electronics Store",
    inStock: true,
  },
];
