import type { StoreDetails } from "./types";

export const MOCK_STORES: Record<string, StoreDetails> = {
  "storee-corner": {
    id: 1,
    name: "Storee Corner",
    slug: "storee-corner",
    tagline: "Cambodia's #1 Premium Smartphone & Gadgets Hub",
    description: "Official authorized retailer for authentic flagship smartphones, tablets, and smart wearables in Phnom Penh. Fast nationwide delivery with official brand warranty.",
    avatarUrl: "/picture/pic1.jpg",
    coverUrl: "/picture/pic2.jpg",
    rating: 4.9,
    reviewCount: 520,
    productCount: 190,
    followersCount: 14200,
    verified: true,
    location: "Street 271, Tuol Sangkae, Phnom Penh",
    joinedYear: "2022",
    responseRate: "99% (Replies in ~15 mins)",
    shippingTime: "Same Day & 1-2 Days Express",
    categories: ["Phone & Tablets", "Computer & Accessories", "Gadgets"],
    products: [
      {
        id: 101,
        slug: "poco-smart-phone-x5-pro",
        title: "POCO Smart Phone X5 Pro 5G 256GB Yellow",
        price: 216.75,
        originalPrice: 255.0,
        discountPercent: 15,
        rating: 4.8,
        reviewCount: 42,
        image: "/picture/pic1.jpg",
        category: "Phone & Tablets",
      },
      {
        id: 102,
        slug: "macbook-pro-16-m3-max",
        title: 'MacBook Pro 16" M3 Max 36GB / 1TB SSD - Space Black',
        price: 2499.0,
        rating: 5.0,
        reviewCount: 18,
        image: "/picture/pic2.jpg",
        category: "Computer & Accessories",
      },
      {
        id: 103,
        slug: "sony-wh-1000xm5-wireless-headphones",
        title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
        price: 307.12,
        originalPrice: 349.0,
        discountPercent: 12,
        rating: 4.9,
        reviewCount: 64,
        image: "/picture/pic7.jpg",
        category: "Gadgets",
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "Vanneth Sok",
        rating: 5,
        date: "Aug 14, 2026",
        comment: "Excellent service! Phone delivered within 2 hours in Phnom Penh. Genuine product with warranty sealed.",
        productName: "POCO Smart Phone X5 Pro 5G",
      },
      {
        id: 2,
        userName: "Sreypov Meas",
        rating: 5,
        date: "Jul 29, 2026",
        comment: "Very friendly store seller, quick chat response on Phsar Digital!",
        productName: "MacBook Pro 16 M3",
      },
    ],
  },

  "dance-skirts": {
    id: 2,
    name: "Dance skirts",
    slug: "dance-skirts",
    tagline: "Elegant Fashion & Contemporary Apparel",
    description: "Trendy women's apparel, summer dresses, skirts, and handcrafted accessories. Designed with comfort and modern Khmer style in mind.",
    fullStory: "Founded in 2023 in Phnom Penh, Dance Skirts has grown to become one of Cambodia's favorite online fashion boutiques. We specialize in high-quality, breathable fabrics tailored for the Southeast Asian climate, blending classic Khmer aesthetics with chic global fashion trends. Every piece is carefully inspected to ensure top-notch stitching and long-lasting quality.",
    avatarUrl: "/picture/pic4.jpg",
    coverUrl: "/picture/pic3.jpg",
    rating: 4.8,
    reviewCount: 380,
    productCount: 190,
    followersCount: 9800,
    verified: true,
    location: "Boeung Keng Kang 1, Phnom Penh",
    fullAddress: "House #14, Street 310, Sangkat Boeung Keng Kang 1, Khan Chamkarmon, Phnom Penh, Cambodia",
    businessHours: "Monday – Sunday: 8:00 AM – 8:30 PM",
    joinedYear: "2023",
    responseRate: "97% (Replies within 1 hour)",
    shippingTime: "1-2 Business Days Express",
    categories: ["Fashion & Beauty", "Dress & Skirts", "Accessories"],
    products: [
      {
        id: 201,
        slug: "women-s-floral-summer-dress",
        title: "Women's Floral Lightweight Summer Skirt Dress",
        price: 45.0,
        originalPrice: 60.0,
        discountPercent: 25,
        rating: 4.9,
        reviewCount: 78,
        image: "/picture/pic3.jpg",
        category: "Fashion & Beauty",
      },
      {
        id: 202,
        slug: "fitbit-versa-4-fitness-smartwatch",
        title: "Fitbit Versa 4 Rose Gold Fashion Edition",
        price: 97.2,
        originalPrice: 108.0,
        discountPercent: 10,
        rating: 4.6,
        reviewCount: 29,
        image: "/picture/pic4.jpg",
        category: "Accessories",
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "Chanda Chea",
        rating: 5,
        date: "Aug 02, 2026",
        comment: "Beautiful skirt fabric and perfect fit! Highly recommended seller.",
        productName: "Women's Floral Summer Skirt",
      },
    ],
  },

  "skatery": {
    id: 3,
    name: "Skatery",
    slug: "skatery",
    tagline: "Streetwear, Sneakers & Urban Tech",
    description: "Your go-to store for authentic sneakers, urban streetwear, high-performance laptops, and audio gear.",
    avatarUrl: "/picture/pic5.jpg",
    coverUrl: "/picture/pic6.jpg",
    rating: 4.9,
    reviewCount: 450,
    productCount: 190,
    followersCount: 18500,
    verified: true,
    location: "Toul Kork, Phnom Penh",
    joinedYear: "2022",
    responseRate: "98%",
    shippingTime: "Express 1 Day",
    categories: ["Fashion & Beauty", "Shoes & Sneakers", "Computer & Accessories"],
    products: [
      {
        id: 301,
        slug: "nike-air-zoom-pegasus-40",
        title: "Nike Air Zoom Pegasus 40 Road Running Shoes",
        price: 130.0,
        rating: 4.7,
        reviewCount: 35,
        image: "/picture/pic3.jpg",
        category: "Shoes & Sneakers",
      },
      {
        id: 302,
        slug: "laptop-pro-gaming",
        title: "Ultra Slim Workstation Laptop 16GB RAM",
        price: 899.0,
        originalPrice: 999.0,
        discountPercent: 10,
        rating: 4.8,
        reviewCount: 52,
        image: "/picture/pic5.jpg",
        category: "Computer & Accessories",
      },
    ],
    reviews: [],
  },

  "flowero": {
    id: 4,
    name: "Flowero",
    slug: "flowero",
    tagline: "Home Electronics, Decor & Smart Appliances",
    description: "Transform your living space with smart TVs, home appliances, kitchen tools, and premium living accessories.",
    avatarUrl: "/picture/pic8.jpg",
    coverUrl: "/picture/pic7.jpg",
    rating: 4.7,
    reviewCount: 290,
    productCount: 190,
    followersCount: 7600,
    verified: true,
    location: "Chroy Changvar, Phnom Penh",
    joinedYear: "2023",
    responseRate: "95%",
    shippingTime: "2-3 Days Heavy Goods Delivery",
    categories: ["Electronic & Appliances", "Home & Kitchen", "Furniture & Decor"],
    products: [
      {
        id: 401,
        slug: "lg-smart-oled-4k-tv-55",
        title: 'LG OLED evo C3 55" 4K Smart TV 2024 Model',
        price: 559.2,
        originalPrice: 699.0,
        discountPercent: 20,
        rating: 4.8,
        reviewCount: 51,
        image: "/picture/pic8.jpg",
        category: "Electronic & Appliances",
      },
      {
        id: 402,
        slug: "sony-wh-1000xm5-wireless-headphones",
        title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
        price: 307.12,
        originalPrice: 349.0,
        discountPercent: 12,
        rating: 4.9,
        reviewCount: 64,
        image: "/picture/pic7.jpg",
        category: "Electronic & Appliances",
      },
    ],
    reviews: [],
  },
};

// Default fallback store for unknown slugs
export const DEFAULT_STORE_DETAILS: StoreDetails = {
  id: 99,
  name: "Phsar Digital Verified Store",
  slug: "official-store",
  tagline: "Official Phsar Digital Vendor",
  description: "Verified Phsar Digital Marketplace Seller providing high quality products, fast nationwide shipping, and buyer protection.",
  avatarUrl: "/picture/pic1.jpg",
  coverUrl: "/picture/pic2.jpg",
  rating: 4.9,
  reviewCount: 320,
  productCount: 150,
  followersCount: 12500,
  verified: true,
  location: "Phnom Penh, Cambodia",
  joinedYear: "2023",
  responseRate: "98%",
  shippingTime: "1-2 Days Express",
  categories: ["All Categories"],
  products: [
    {
      id: 901,
      slug: "poco-smart-phone-x5-pro",
      title: "POCO Smart Phone X5 Pro 5G 256GB Yellow",
      price: 216.75,
      originalPrice: 255.0,
      discountPercent: 15,
      rating: 4.8,
      reviewCount: 42,
      image: "/picture/pic1.jpg",
      category: "Phone & Tablets",
    },
    {
      id: 902,
      slug: "macbook-pro-16-m3-max",
      title: 'MacBook Pro 16" M3 Max 36GB / 1TB SSD - Space Black',
      price: 2499.0,
      rating: 5.0,
      reviewCount: 18,
      image: "/picture/pic2.jpg",
      category: "Computer & Accessories",
    },
  ],
  reviews: [],
};
