export interface CuratedProduct {
  uuid: string;
  slug: string;
  title: string;
  description: string;
  image: string;
  thumbnailUri: { uri: string };
  images: { id: number; url: string; isPrimary: boolean; is_primary: boolean }[];
  fullPrice: number;
  discountPrice: number | null;
  price: number;
  stockQty: number;
  status: string;
  isFeatured: boolean;
  category: { name: string; slug: string };
  sellerProfile: {
    businessName: string;
    sellerId: string;
  };
  sellerName?: string;
  averageRating: number;
  reviewCount: number;
  isFavorite: boolean;
  sold?: number;
}

export const CURATED_PRODUCTS: CuratedProduct[] = [
  // ================= PINTEREST TRENDING FAVORITES =================
  {
    uuid: "prod-leather-crossbody",
    slug: "minimalist-grain-leather-crossbody-saddle-bag",
    title: "Minimalist Grain Leather Crossbody Saddle Bag",
    description: "Handcrafted from rich full-grain pebbled leather with polished gold hardware accents, adjustable shoulder strap, and magnetic flap closure with secure inner zip compartments.",
    image: "/picture/product_leather_crossbody.jpg",
    thumbnailUri: { uri: "/picture/product_leather_crossbody.jpg" },
    images: [
      { id: 301, url: "/picture/product_leather_crossbody.jpg", isPrimary: true, is_primary: true },
      { id: 302, url: "/picture/product_leather_crossbody.jpg", isPrimary: false, is_primary: false },
    ],
    fullPrice: 85.00,
    discountPrice: 58.00,
    price: 58.00,
    stockQty: 25,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Women's Fashion", slug: "womens-fashion" },
    sellerProfile: { businessName: "Aesthete Studio", sellerId: "seller-30" },
    averageRating: 5.0,
    reviewCount: 47,
    isFavorite: true,
    sold: 135,
  },
  {
    uuid: "prod-knit-sweater",
    slug: "cozy-cable-knit-oversized-wool-sweater",
    title: "Cozy Cable-Knit Oversized Wool Sweater",
    description: "Chunky textured cable-knit sweater spun from an ultra-soft premium merino wool blend. Features a relaxed slouchy silhouette, ribbed crewneck, and cozy drop shoulders.",
    image: "/picture/product_knit_sweater.jpg",
    thumbnailUri: { uri: "/picture/product_knit_sweater.jpg" },
    images: [
      { id: 303, url: "/picture/product_knit_sweater.jpg", isPrimary: true, is_primary: true },
    ],
    fullPrice: 68.00,
    discountPrice: 46.00,
    price: 46.00,
    stockQty: 30,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Women's Fashion", slug: "womens-fashion" },
    sellerProfile: { businessName: "Maison Knitwear", sellerId: "seller-31" },
    averageRating: 4.9,
    reviewCount: 38,
    isFavorite: true,
    sold: 95,
  },
  {
    uuid: "prod-designer-sneakers",
    slug: "minimalist-leather-low-top-designer-sneakers",
    title: "Minimalist Leather Low-Top Designer Sneakers",
    description: "Timeless Italian-inspired luxury white sneakers crafted with supple calfskin leather uppers, durable stitched gum rubber cupsole, and cushioned memory foam insole.",
    image: "/picture/product_designer_sneakers.jpg",
    thumbnailUri: { uri: "/picture/product_designer_sneakers.jpg" },
    images: [
      { id: 304, url: "/picture/product_designer_sneakers.jpg", isPrimary: true, is_primary: true },
    ],
    fullPrice: 98.00,
    discountPrice: 72.00,
    price: 72.00,
    stockQty: 40,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Sports & Outdoors", slug: "sports-and-outdoors" },
    sellerProfile: { businessName: "Sneaker World", sellerId: "seller-16" },
    averageRating: 4.9,
    reviewCount: 62,
    isFavorite: false,
    sold: 180,
  },
  {
    uuid: "prod-rosegold-watch",
    slug: "luxury-rose-gold-minimalist-mesh-quartz-watch",
    title: "Luxury Rose Gold Minimalist Mesh Quartz Watch",
    description: "Sleek contemporary timepiece featuring a Japanese quartz movement, clean white sunray dial with date window, and a fluid rose gold stainless steel milanese mesh strap.",
    image: "/picture/product_rosegold_watch.jpg",
    thumbnailUri: { uri: "/picture/product_rosegold_watch.jpg" },
    images: [
      { id: 305, url: "/picture/product_rosegold_watch.jpg", isPrimary: true, is_primary: true },
    ],
    fullPrice: 135.00,
    discountPrice: 89.00,
    price: 89.00,
    stockQty: 20,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Women's Fashion", slug: "womens-fashion" },
    sellerProfile: { businessName: "Aeterna Timepieces", sellerId: "seller-32" },
    averageRating: 5.0,
    reviewCount: 53,
    isFavorite: true,
    sold: 110,
  },
  {
    uuid: "prod-glow-serum",
    slug: "organic-botanical-olive-glow-hydrating-serum",
    title: "Organic Botanical Olive & Glow Hydrating Face Serum",
    description: "Clean restorative facial elixir enriched with cold-pressed squalane, botanical olive leaf extract, and multi-weight hyaluronic acid for instant radiant glass skin.",
    image: "/picture/product_glow_serum.jpg",
    thumbnailUri: { uri: "/picture/product_glow_serum.jpg" },
    images: [
      { id: 306, url: "/picture/product_glow_serum.jpg", isPrimary: true, is_primary: true },
    ],
    fullPrice: 55.00,
    discountPrice: 38.00,
    price: 38.00,
    stockQty: 50,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Health & Beauty", slug: "health-and-beauty" },
    sellerProfile: { businessName: "Olive & Glow Botanicals", sellerId: "seller-33" },
    averageRating: 4.9,
    reviewCount: 71,
    isFavorite: true,
    sold: 240,
  },

  // ================= 1. BOOKS & STATIONERY =================
  {
    uuid: "prod-book-agile",
    slug: "handbook-agile-software-craftsmanship",
    title: "A Handbook of Agile Software Craftsmanship",
    description: "Essential guide for software developers and engineering leaders covering clean architecture, design patterns, automated testing, and agile team practices.",
    image: "/picture/category_books.jpg",
    thumbnailUri: { uri: "/picture/category_books.jpg" },
    images: [{ id: 15, url: "/picture/category_books.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 38.00,
    discountPrice: 29.99,
    price: 29.99,
    stockQty: 50,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Books & Stationery", slug: "books-and-stationery" },
    sellerProfile: { businessName: "Bookland Press", sellerId: "seller-14" },
    averageRating: 4.9,
    reviewCount: 54,
    isFavorite: false,
    sold: 160,
  },
  {
    uuid: "prod-book-pragmatic",
    slug: "the-pragmatic-programmer-20th-anniversary",
    title: "The Pragmatic Programmer: 20th Anniversary Edition",
    description: "One of the most significant books in modern software development, packed with practical insights on code architecture, career growth, and software craftsmanship.",
    image: "/picture/category_books.jpg",
    thumbnailUri: { uri: "/picture/category_books.jpg" },
    images: [{ id: 201, url: "/picture/category_books.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 45.00,
    discountPrice: 34.99,
    price: 34.99,
    stockQty: 40,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Books & Stationery", slug: "books-and-stationery" },
    sellerProfile: { businessName: "Bookland Press", sellerId: "seller-14" },
    averageRating: 5.0,
    reviewCount: 78,
    isFavorite: false,
    sold: 210,
  },
  {
    uuid: "prod-bullet-journal",
    slug: "hardcover-dot-grid-bullet-journal-a5",
    title: "Hardcover Minimalist Dot Grid Bullet Journal (A5)",
    description: "Premium 160gsm bleed-proof bamboo paper notebook with numbered pages, inner expandable pocket, dual ribbon bookmarks, and elastic closure band.",
    image: "/picture/category_books.jpg",
    thumbnailUri: { uri: "/picture/category_books.jpg" },
    images: [{ id: 202, url: "/picture/category_books.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 20.00,
    discountPrice: 14.50,
    price: 14.50,
    stockQty: 85,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Books & Stationery", slug: "books-and-stationery" },
    sellerProfile: { businessName: "Artisan Stationery", sellerId: "seller-20" },
    averageRating: 4.8,
    reviewCount: 39,
    isFavorite: true,
    sold: 140,
  },
  {
    uuid: "prod-fountain-pen",
    slug: "vintage-brass-fountain-pen-ink-set",
    title: "Vintage Brass Fountain Pen with Blue Ink Bottle Set",
    description: "Exquisite hand-polished solid brass fountain pen with fine iridium nib, smooth ink flow, refillable ink converter, and 50ml archival midnight blue ink.",
    image: "/picture/category_books.jpg",
    thumbnailUri: { uri: "/picture/category_books.jpg" },
    images: [{ id: 203, url: "/picture/category_books.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 39.00,
    discountPrice: 28.00,
    price: 28.00,
    stockQty: 30,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Books & Stationery", slug: "books-and-stationery" },
    sellerProfile: { businessName: "Artisan Stationery", sellerId: "seller-20" },
    averageRating: 4.9,
    reviewCount: 22,
    isFavorite: false,
    sold: 65,
  },

  // ================= 2. TOYS & BABY CARE =================
  {
    uuid: "prod-wooden-blocks",
    slug: "educational-wooden-building-blocks-puzzle",
    title: "Educational Wooden Building Blocks & Puzzle Set",
    description: "100-piece natural beechwood geometric building blocks with non-toxic water-based pastel paint. Encourages spatial reasoning, motor skills, and creativity.",
    image: "/picture/pic8.jpg",
    thumbnailUri: { uri: "/picture/pic8.jpg" },
    images: [{ id: 204, url: "/picture/pic8.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 35.00,
    discountPrice: 24.99,
    price: 24.99,
    stockQty: 45,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Toys & Baby Care", slug: "toys-and-baby-care" },
    sellerProfile: { businessName: "Little Explorers", sellerId: "seller-21" },
    averageRating: 4.9,
    reviewCount: 42,
    isFavorite: false,
    sold: 110,
  },
  {
    uuid: "prod-baby-carrier",
    slug: "ergonomic-multi-position-baby-carrier",
    title: "Ergonomic Multi-Position Baby Carrier with Lumbar Support",
    description: "Breathable 3D mesh baby carrier designed for newborns to toddlers (7–45 lbs). Features padded crossable shoulder straps and ergonomic hip seat support.",
    image: "/picture/pic8.jpg",
    thumbnailUri: { uri: "/picture/pic8.jpg" },
    images: [{ id: 205, url: "/picture/pic8.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 65.00,
    discountPrice: 48.00,
    price: 48.00,
    stockQty: 25,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Toys & Baby Care", slug: "toys-and-baby-care" },
    sellerProfile: { businessName: "Little Explorers", sellerId: "seller-21" },
    averageRating: 4.8,
    reviewCount: 31,
    isFavorite: true,
    sold: 80,
  },

  // ================= 3. GROCERIES & ESSENTIALS =================
  {
    uuid: "prod-cambodian-coffee",
    slug: "specialty-roasted-cambodian-coffee-beans",
    title: "Specialty Roasted Arabica Coffee Beans (500g)",
    description: "Direct-trade high-altitude Mondulkiri single-origin Arabica coffee beans, small-batch medium roasted with rich notes of dark chocolate and toasted caramel.",
    image: "/picture/seller_cover_coffee.jpg",
    thumbnailUri: { uri: "/picture/seller_cover_coffee.jpg" },
    images: [{ id: 14, url: "/picture/seller_cover_coffee.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 28.00,
    discountPrice: 22.00,
    price: 22.00,
    stockQty: 100,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Groceries & Essentials", slug: "groceries-and-essentials" },
    sellerProfile: { businessName: "SOMA Coffee & Roastery", sellerId: "seller-13" },
    averageRating: 4.9,
    reviewCount: 88,
    isFavorite: true,
    sold: 430,
  },
  {
    uuid: "prod-kampot-pepper",
    slug: "organic-cambodian-kampot-black-pepper",
    title: "Organic Cambodian Kampot Black Pepper (200g Jar)",
    description: "PGI-certified premium sun-dried Kampot black peppercorns from certified organic farms, known for their intense aroma, subtle floral bouquet, and deep warmth.",
    image: "/picture/seller_cover_coffee.jpg",
    thumbnailUri: { uri: "/picture/seller_cover_coffee.jpg" },
    images: [{ id: 206, url: "/picture/seller_cover_coffee.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 20.00,
    discountPrice: 15.00,
    price: 15.00,
    stockQty: 70,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Groceries & Essentials", slug: "groceries-and-essentials" },
    sellerProfile: { businessName: "SOMA Coffee & Roastery", sellerId: "seller-13" },
    averageRating: 5.0,
    reviewCount: 49,
    isFavorite: false,
    sold: 195,
  },
  {
    uuid: "prod-wildflower-honey",
    slug: "raw-wildflower-honey-wooden-dipper",
    title: "Raw Pure Wildflower Honey Jar with Wooden Dipper (350g)",
    description: "100% pure unfiltered raw honey harvested sustainably from wild forest blossoms. Rich in natural enzymes, antioxidants, and delicate floral sweetness.",
    image: "/picture/seller_cover_coffee.jpg",
    thumbnailUri: { uri: "/picture/seller_cover_coffee.jpg" },
    images: [{ id: 207, url: "/picture/seller_cover_coffee.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 24.00,
    discountPrice: 17.50,
    price: 17.50,
    stockQty: 60,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Groceries & Essentials", slug: "groceries-and-essentials" },
    sellerProfile: { businessName: "SOMA Coffee & Roastery", sellerId: "seller-13" },
    averageRating: 4.9,
    reviewCount: 35,
    isFavorite: false,
    sold: 120,
  },

  // ================= 4. HEALTH & BEAUTY =================
  {
    uuid: "prod-botanical-serum",
    slug: "luxury-organic-botanical-facial-serum",
    title: "Luxury Organic Botanical Facial Essence & Serum",
    description: "Deeply nourishing facial treatment formulated with cold-pressed botanical extracts, hyaluronic acid, and vitamin C for instant glow and barrier restoration.",
    image: "/picture/hero_natural_care.jpg",
    thumbnailUri: { uri: "/picture/hero_natural_care.jpg" },
    images: [{ id: 12, url: "/picture/hero_natural_care.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 110.00,
    discountPrice: 75.00,
    price: 75.00,
    stockQty: 40,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Health & Beauty", slug: "health-and-beauty" },
    sellerProfile: { businessName: "Aura Naturals", sellerId: "seller-11" },
    averageRating: 5.0,
    reviewCount: 64,
    isFavorite: false,
    sold: 175,
  },
  {
    uuid: "prod-face-oil",
    slug: "aquamarine-deep-moisture-night-cream",
    title: "Aquamarine Deep Moisture Restoring Face Oil",
    description: "Lightweight, non-comedogenic luxury facial oil packed with blue tansy and squalane to soothe redness and lock in 24-hour hydration overnight.",
    image: "/picture/hero_slide_summer_sale.jpg",
    thumbnailUri: { uri: "/picture/hero_slide_summer_sale.jpg" },
    images: [{ id: 13, url: "/picture/hero_slide_summer_sale.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 95.00,
    discountPrice: 62.00,
    price: 62.00,
    stockQty: 35,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Health & Beauty", slug: "health-and-beauty" },
    sellerProfile: { businessName: "Storee Corner", sellerId: "seller-12" },
    averageRating: 4.7,
    reviewCount: 19,
    isFavorite: false,
    sold: 45,
  },
  {
    uuid: "prod-inhaler-set",
    slug: "minimalist-aromatherapy-nasal-inhaler-set",
    title: "Minimalist Aromatherapy Herbal Nasal Inhaler Set",
    description: "Natural herbal aromatherapy inhalers infused with peppermint, eucalyptus, and menthol essential oils for quick nasal congestion relief and focus.",
    image: "/picture/hero_inhaler_promo.jpg",
    thumbnailUri: { uri: "/picture/hero_inhaler_promo.jpg" },
    images: [{ id: 105, url: "/picture/hero_inhaler_promo.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 35.00,
    discountPrice: 24.00,
    price: 24.00,
    stockQty: 50,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Health & Beauty", slug: "health-and-beauty" },
    sellerProfile: { businessName: "Aura Naturals", sellerId: "seller-11" },
    averageRating: 4.8,
    reviewCount: 28,
    isFavorite: false,
    sold: 88,
  },

  // ================= 5. HOME & LIVING =================
  {
    uuid: "prod-scented-candle",
    slug: "cedarwood-bergamot-scented-soy-candle",
    title: "Cedarwood & Bergamot Soy Wax Scented Candle",
    description: "Hand-poured 100% natural soy wax candle in an amber glass jar with natural wood lid. Infused with pure essential oils for a relaxing 45-hour clean burn.",
    image: "/picture/product_scented_candle.jpg",
    thumbnailUri: { uri: "/picture/product_scented_candle.jpg" },
    images: [{ id: 9, url: "/picture/product_scented_candle.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 22.00,
    discountPrice: 16.00,
    price: 16.00,
    stockQty: 55,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Home & Living", slug: "home-and-living" },
    sellerProfile: { businessName: "Lumina Botanics", sellerId: "seller-9" },
    averageRating: 5.0,
    reviewCount: 61,
    isFavorite: true,
    sold: 145,
  },
  {
    uuid: "prod-coffee-mug",
    slug: "ceramic-coffee-mug-saucer-set",
    title: "Scandinavian Ceramic Coffee Mug & Saucer Set",
    description: "Artisan stoneware 350ml ceramic coffee mug with matching saucer and wooden stirring spoon. Microwave and dishwasher safe with matte glaze finish.",
    image: "/picture/pic2.jpg",
    thumbnailUri: { uri: "/picture/pic2.jpg" },
    images: [{ id: 18, url: "/picture/pic2.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 20.00,
    discountPrice: 14.99,
    price: 14.99,
    stockQty: 60,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Home & Living", slug: "home-and-living" },
    sellerProfile: { businessName: "Nordic Living", sellerId: "seller-17" },
    averageRating: 4.8,
    reviewCount: 26,
    isFavorite: false,
    sold: 80,
  },
  {
    uuid: "prod-kitchen-tongs",
    slug: "stainless-steel-kitchen-cooking-tongs",
    title: "Stainless Steel Kitchen Food Tongs (Non-Stick)",
    description: "Heavy duty 304 stainless steel kitchen tongs with heat-resistant silicone scalloped tips and pull-ring locking mechanism for grilling and cooking.",
    image: "/picture/pic3.jpg",
    thumbnailUri: { uri: "/picture/pic3.jpg" },
    images: [{ id: 19, url: "/picture/pic3.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 12.00,
    discountPrice: 8.50,
    price: 8.50,
    stockQty: 90,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Home & Living", slug: "home-and-living" },
    sellerProfile: { businessName: "Chef Essentials", sellerId: "seller-18" },
    averageRating: 4.7,
    reviewCount: 33,
    isFavorite: false,
    sold: 110,
  },

  // ================= 6. SPORTS & OUTDOORS =================
  {
    uuid: "prod-travel-backpack",
    slug: "waterproof-travel-laptop-backpack",
    title: "Waterproof Travel Laptop Backpack",
    description: "Ergonomic water-resistant travel backpack with padded 15.6-inch laptop compartment, hidden anti-theft pockets, USB charging pass-through, and breathable mesh back panel.",
    image: "/picture/product_travel_backpack.jpg",
    thumbnailUri: { uri: "/picture/product_travel_backpack.jpg" },
    images: [{ id: 4, url: "/picture/product_travel_backpack.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 45.00,
    discountPrice: 35.00,
    price: 35.00,
    stockQty: 28,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Sports & Outdoors", slug: "sports-and-outdoors" },
    sellerProfile: { businessName: "Aero Luggage & Bags", sellerId: "seller-4" },
    averageRating: 4.9,
    reviewCount: 53,
    isFavorite: false,
    sold: 140,
  },
  {
    uuid: "prod-water-bottle",
    slug: "insulated-stainless-steel-sports-water-bottle",
    title: "Insulated Stainless Steel Sports Water Bottle",
    description: "Double-wall vacuum insulated 24oz sports bottle keeping beverages ice cold for 24 hours or piping hot for 12 hours. Features leak-proof spout lid and carry handle.",
    image: "/picture/product_water_bottle.jpg",
    thumbnailUri: { uri: "/picture/product_water_bottle.jpg" },
    images: [{ id: 8, url: "/picture/product_water_bottle.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 24.00,
    discountPrice: 18.00,
    price: 18.00,
    stockQty: 75,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Sports & Outdoors", slug: "sports-and-outdoors" },
    sellerProfile: { businessName: "HydratePro Essentials", sellerId: "seller-8" },
    averageRating: 4.9,
    reviewCount: 46,
    isFavorite: false,
    sold: 180,
  },
  {
    uuid: "prod-running-shoes",
    slug: "ultralight-breathable-running-shoes",
    title: "Ultralight Breathable Running Shoes",
    description: "Engineered knit upper running shoes with responsive foam cushioning, shock-absorbing traction outsole, and antimicrobial moisture-wicking insole.",
    image: "/picture/pic7.jpg",
    thumbnailUri: { uri: "/picture/pic7.jpg" },
    images: [{ id: 17, url: "/picture/pic7.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 89.00,
    discountPrice: 68.00,
    price: 68.00,
    stockQty: 45,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Sports & Outdoors", slug: "sports-and-outdoors" },
    sellerProfile: { businessName: "Sneaker World", sellerId: "seller-16" },
    averageRating: 4.9,
    reviewCount: 41,
    isFavorite: false,
    sold: 90,
  },

  // ================= 7. VEHICLES & AUTO =================
  {
    uuid: "prod-car-dashcam",
    slug: "universal-car-dashcam-night-vision",
    title: "Universal 1080P Car Dashcam with Night Vision",
    description: "Full HD 1080P car dashboard camera with 170-degree wide angle lens, G-sensor emergency collision lock, loop recording, and enhanced night vision.",
    image: "/picture/seller_cover_auto.jpg",
    thumbnailUri: { uri: "/picture/seller_cover_auto.jpg" },
    images: [{ id: 20, url: "/picture/seller_cover_auto.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 65.00,
    discountPrice: 49.00,
    price: 49.00,
    stockQty: 30,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Vehicles", slug: "vehicles" },
    sellerProfile: { businessName: "AutoPro Hub", sellerId: "seller-19" },
    averageRating: 4.8,
    reviewCount: 37,
    isFavorite: false,
    sold: 72,
  },
  {
    uuid: "prod-car-mount",
    slug: "magnetic-car-air-vent-phone-mount",
    title: "Magnetic Car Air Vent Phone Mount (360° Rotation)",
    description: "Ultra-strong neodymium magnetic phone mount with rubberized anti-scratch air vent clamp and 360-degree ball joint rotation for safe hands-free navigation.",
    image: "/picture/seller_cover_auto.jpg",
    thumbnailUri: { uri: "/picture/seller_cover_auto.jpg" },
    images: [{ id: 208, url: "/picture/seller_cover_auto.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 18.00,
    discountPrice: 12.00,
    price: 12.00,
    stockQty: 65,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Vehicles", slug: "vehicles" },
    sellerProfile: { businessName: "AutoPro Hub", sellerId: "seller-19" },
    averageRating: 4.7,
    reviewCount: 29,
    isFavorite: false,
    sold: 130,
  },

  // ================= 8. ELECTRONICS =================
  {
    uuid: "ac364012-6788-4df9-baf9-a7815753d9c1",
    slug: "wireless-mechanical-gaming-keyboard",
    title: "Wireless Mechanical Gaming Keyboard (RGB Backlit)",
    description: "Compact 75% wireless mechanical keyboard with hot-swappable switches, sound-dampening foam gaskets, multi-device Bluetooth & 2.4GHz connectivity, and customizable dynamic RGB lighting.",
    image: "/picture/product_wireless_earbuds.jpg",
    thumbnailUri: { uri: "/picture/product_wireless_earbuds.jpg" },
    images: [{ id: 102, url: "/picture/product_wireless_earbuds.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 119.99,
    discountPrice: 89.99,
    price: 89.99,
    stockQty: 35,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Electronics", slug: "electronics" },
    sellerProfile: { businessName: "TechHub Electronics", sellerId: "seller-3" },
    averageRating: 4.9,
    reviewCount: 48,
    isFavorite: true,
    sold: 160,
  },
  {
    uuid: "prod-wireless-headphones",
    slug: "bluetooth-wireless-noise-cancelling-headphones",
    title: "Bluetooth Wireless Noise-Cancelling Headphones",
    description: "Studio-grade wireless over-ear headphones featuring active noise cancellation (ANC), deep bass response, 40-hour battery life, and ultra-plush memory foam ear cushions.",
    image: "/picture/seller_cover_electronics.jpg",
    thumbnailUri: { uri: "/picture/seller_cover_electronics.jpg" },
    images: [{ id: 3, url: "/picture/seller_cover_electronics.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 69.99,
    discountPrice: 49.99,
    price: 49.99,
    stockQty: 60,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Electronics", slug: "electronics" },
    sellerProfile: { businessName: "TechHub Electronics", sellerId: "seller-3" },
    averageRating: 5.0,
    reviewCount: 65,
    isFavorite: false,
    sold: 210,
  },
  {
    uuid: "prod-wireless-earbuds",
    slug: "true-wireless-bluetooth-earbuds",
    title: "True Wireless Bluetooth Earbuds with Case",
    description: "Compact wireless earbuds with crystal-clear stereo sound, IPX5 sweat resistance, touch controls, and compact USB-C quick-charge case delivering 28 hours total playback.",
    image: "/picture/product_wireless_earbuds.jpg",
    thumbnailUri: { uri: "/picture/product_wireless_earbuds.jpg" },
    images: [{ id: 6, url: "/picture/product_wireless_earbuds.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 59.99,
    discountPrice: 42.00,
    price: 42.00,
    stockQty: 80,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Electronics", slug: "electronics" },
    sellerProfile: { businessName: "Aura Audio", sellerId: "seller-6" },
    averageRating: 4.9,
    reviewCount: 74,
    isFavorite: false,
    sold: 310,
  },
  {
    uuid: "prod-smart-watch",
    slug: "smart-fitness-activity-tracker-watch",
    title: "Smart Fitness Activity Tracker & Heart Rate Watch",
    description: "Sleek fitness smartwatch featuring 24/7 heart rate monitoring, SpO2 blood oxygen sensor, sleep tracking, 30+ sports modes, and 10-day battery life on a single charge.",
    image: "/picture/pic4.jpg",
    thumbnailUri: { uri: "/picture/pic4.jpg" },
    images: [{ id: 103, url: "/picture/pic4.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 55.00,
    discountPrice: 38.00,
    price: 38.00,
    stockQty: 40,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Electronics", slug: "electronics" },
    sellerProfile: { businessName: "TechHub Electronics", sellerId: "seller-3" },
    averageRating: 4.8,
    reviewCount: 52,
    isFavorite: false,
    sold: 95,
  },
  {
    uuid: "prod-laptop-m2",
    slug: "ultra-thin-pro-laptop-m2",
    title: "Ultra-Thin Pro Laptop M2 (16GB RAM / 512GB SSD)",
    description: "Featherlight high-performance aluminum laptop powered by an advanced octa-core processor, vivid 13.6-inch Retina display, and 18-hour all-day battery life.",
    image: "/picture/pic8.jpg",
    thumbnailUri: { uri: "/picture/pic8.jpg" },
    images: [{ id: 104, url: "/picture/pic8.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 520.00,
    discountPrice: 399.00,
    price: 399.00,
    stockQty: 15,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Electronics", slug: "electronics" },
    sellerProfile: { businessName: "TechHub Electronics", sellerId: "seller-3" },
    averageRating: 4.9,
    reviewCount: 38,
    isFavorite: false,
    sold: 45,
  },

  // ================= 9. WOMEN'S FASHION =================
  {
    uuid: "prod-summer-dress",
    slug: "floral-summer-midi-wrap-dress",
    title: "Floral Summer Midi Wrap Dress",
    description: "Breathable airy chiffon summer wrap dress featuring vintage floral print, sweetheart neckline, and flattering waist tie. Ideal for garden parties, vacations, and casual outings.",
    image: "/picture/product_dress_blue_floral.jpg",
    thumbnailUri: { uri: "/picture/product_dress_blue_floral.jpg" },
    images: [{ id: 2, url: "/picture/product_dress_blue_floral.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 49.99,
    discountPrice: 39.99,
    price: 39.99,
    stockQty: 32,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Women's Fashion", slug: "womens-fashion" },
    sellerProfile: { businessName: "Fashion By Srey", sellerId: "seller-2" },
    averageRating: 4.8,
    reviewCount: 38,
    isFavorite: true,
    sold: 95,
  },
  {
    uuid: "prod-beige-dress",
    slug: "beige-floral-sweetheart-midi-dress",
    title: "Beige Floral Sweetheart Midi Dress with Leg Slit",
    description: "Elegant lightweight midi dress featuring soft sweetheart neckline, tie-front bodice, and high side leg slit. Flattering silhouette for daytime and evening wear.",
    image: "/picture/product_dress_beige_slit.jpg",
    thumbnailUri: { uri: "/picture/product_dress_beige_slit.jpg" },
    images: [{ id: 10, url: "/picture/product_dress_beige_slit.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 85.00,
    discountPrice: 58.00,
    price: 58.00,
    stockQty: 25,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Women's Fashion", slug: "womens-fashion" },
    sellerProfile: { businessName: "Dance skirts", sellerId: "seller-10" },
    averageRating: 4.8,
    reviewCount: 29,
    isFavorite: false,
    sold: 50,
  },
  {
    uuid: "prod-toile-dress",
    slug: "french-toile-blue-vintage-mini-dress",
    title: "French Toile De Jouy Blue Vintage Mini Dress",
    description: "Timeless vintage-inspired mini dress crafted from structured cotton toile with antique botanical print, tailored bodice, and flared skater hem.",
    image: "/picture/product_dress_toile_blue.jpg",
    thumbnailUri: { uri: "/picture/product_dress_toile_blue.jpg" },
    images: [{ id: 11, url: "/picture/product_dress_toile_blue.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 72.00,
    discountPrice: 52.00,
    price: 52.00,
    stockQty: 30,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Women's Fashion", slug: "womens-fashion" },
    sellerProfile: { businessName: "Dance skirts", sellerId: "seller-10" },
    averageRating: 4.9,
    reviewCount: 32,
    isFavorite: false,
    sold: 62,
  },
  {
    uuid: "prod-rose-gold-watch",
    slug: "rose-gold-square-watch-bracelet-set",
    title: "Rose Gold Square Watch & Elegant Bracelet Set",
    description: "Sleek minimalist square dial quartz watch with stainless steel mesh strap, bundled with matching crystal-accented bangle bracelet.",
    image: "/picture/pic5.jpg",
    thumbnailUri: { uri: "/picture/pic5.jpg" },
    images: [{ id: 16, url: "/picture/pic5.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 129.00,
    discountPrice: 89.00,
    price: 89.00,
    stockQty: 20,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Women's Fashion", slug: "womens-fashion" },
    sellerProfile: { businessName: "Jewel & Co.", sellerId: "seller-15" },
    averageRating: 4.8,
    reviewCount: 15,
    isFavorite: false,
    sold: 38,
  },

  // ================= 10. MEN'S FASHION =================
  {
    uuid: "prod-mens-hoodie",
    slug: "mens-cotton-zip-up-hoodie",
    title: "Men's Cotton Zip-Up Hoodie",
    description: "Classic premium heavyweight cotton fleece hoodie with durable zip closure, kangaroo pockets, and adjustable drawstring hood. Perfect for casual everyday wear and lounging.",
    image: "/picture/product_mens_hoodie.jpg",
    thumbnailUri: { uri: "/picture/product_mens_hoodie.jpg" },
    images: [{ id: 1, url: "/picture/product_mens_hoodie.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 39.99,
    discountPrice: 29.99,
    price: 29.99,
    stockQty: 45,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Men's Fashion", slug: "mens-fashion" },
    sellerProfile: { businessName: "Urban Classics Store", sellerId: "seller-1" },
    averageRating: 4.9,
    reviewCount: 42,
    isFavorite: false,
    sold: 120,
  },
  {
    uuid: "prod-oxford-shirt",
    slug: "classic-slim-fit-oxford-cotton-shirt",
    title: "Classic Slim-Fit Oxford Cotton Shirt",
    description: "Tailored 100% combed cotton Oxford shirt with button-down collar and durable pearlized buttons. Versatile design suitable for both formal business and casual styling.",
    image: "/picture/pic6.jpg",
    thumbnailUri: { uri: "/picture/pic6.jpg" },
    images: [{ id: 5, url: "/picture/pic6.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 42.00,
    discountPrice: 34.00,
    price: 34.00,
    stockQty: 50,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Men's Fashion", slug: "mens-fashion" },
    sellerProfile: { businessName: "Gentleman's Choice", sellerId: "seller-5" },
    averageRating: 4.7,
    reviewCount: 29,
    isFavorite: false,
    sold: 85,
  },
  {
    uuid: "prod-leather-wallet",
    slug: "vintage-genuine-leather-bifold-wallet",
    title: "Vintage Genuine Leather Bifold Wallet",
    description: "Handcrafted full-grain leather wallet equipped with RFID-blocking protection, multiple card slots, clear ID window, and dual currency compartments.",
    image: "/picture/product_leather_wallet.jpg",
    thumbnailUri: { uri: "/picture/product_leather_wallet.jpg" },
    images: [{ id: 7, url: "/picture/product_leather_wallet.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 32.00,
    discountPrice: 24.50,
    price: 24.50,
    stockQty: 40,
    status: "ACTIVE",
    isFeatured: false,
    category: { name: "Men's Fashion", slug: "mens-fashion" },
    sellerProfile: { businessName: "Oak & Iron Leather", sellerId: "seller-7" },
    averageRating: 4.8,
    reviewCount: 31,
    isFavorite: false,
    sold: 67,
  },
  {
    uuid: "prod-bomber-jacket",
    slug: "mens-urban-windproof-bomber-jacket",
    title: "Men's Urban Windproof Bomber Jacket",
    description: "Weather-resistant lightweight bomber jacket with ribbed collar, cuffs, and hem. Features dual side zip pockets and sleek water-repellent nylon outer shell.",
    image: "/picture/product_mens_hoodie.jpg",
    thumbnailUri: { uri: "/picture/product_mens_hoodie.jpg" },
    images: [{ id: 101, url: "/picture/product_mens_hoodie.jpg", isPrimary: true, is_primary: true }],
    fullPrice: 65.00,
    discountPrice: 49.99,
    price: 49.99,
    stockQty: 30,
    status: "ACTIVE",
    isFeatured: true,
    category: { name: "Men's Fashion", slug: "mens-fashion" },
    sellerProfile: { businessName: "Urban Classics Store", sellerId: "seller-1" },
    averageRating: 4.9,
    reviewCount: 36,
    isFavorite: true,
    sold: 115,
  },
];
